services:
  - type: web
    name: chvendas
    runtime: node
    buildCommand: npm install && pip install --upgrade pip && pip install -r requirements.txt
    startCommand: node server.js
    envVars:
      - key: SESSION_SECRET
        generateValue: true